version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "5432:5432"
  app:
    image: node-cms-app
    ports: 
      - 8080:8080

